# Generated by Django 4.2.7 on 2026-01-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#fab3c2', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#f89fb5', help_text='Secondary color (hex)', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Main text color (hex)', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Background color (hex)', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
