# Generated by Django 4.2.8 on 2026-05-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_birthday_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PricingPlan',
            new_name='ThemePackage',
        ),
        migrations.CreateModel(
            name='ThemeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.themepackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
