# Generated by Django 4.2.8 on 2026-05-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_themepackage_theme_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayparty',
            name='location_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='birthdayparty',
            name='location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='birthdayparty',
            name='party_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
