# Generated by Django 4.2.8 on 2026-05-31 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_birthdayparty_location_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('token_type', models.CharField(choices=[('magic_link', 'Magic Link'), ('session', 'Session')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='api.birthdayparty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
