# Generated by Django 4.2.8 on 2026-06-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_update_birthday_theme_price'),
        ('api', '0012_giftitem'),
    ]

    operations = [
    ]
