# Generated by Django 4.2.8 on 2026-06-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_0011_update_birthday_theme_price_0012_giftitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayparty',
            name='gift_registry_url',
            field=models.URLField(blank=True),
        ),
    ]
