# Generated by Django 4.2.8 on 2026-06-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_birthdayparty_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostaccesstoken',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_tokens', to='api.birthdayparty'),
        ),
    ]
