# Generated by Django 4.2.8 on 2026-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_wedding_party_schedule_faq_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayparty',
            name='cashapp_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='birthdayparty',
            name='venmo_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
