# Generated by Django 4.2.7 on 2026-06-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_slug_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyshowerevent',
            name='overall_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
