# Generated by Django 4.2.7 on 2026-06-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_babyshowerscheduleitem_babyshowerchecklistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyshowerevent',
            name='host_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='babyshowerevent',
            name='pinterest_board_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='BabyShowerVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='api.babyshowerevent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BabyShowerThankYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver_name', models.CharField(max_length=200)),
                ('gift_description', models.CharField(blank=True, max_length=300)),
                ('thank_you_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thank_yous', to='api.babyshowerevent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BabyShowerDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('task', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.babyshowerevent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
