# Generated by Django 4.2.7 on 2026-06-15 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_host_planning_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyshowerphoto',
            name='delete_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='partyphoto',
            name='delete_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='weddingphoto',
            name='delete_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
